trigger:
- master  # Replace with your desired branch

pool: name

parameters:
- name: resourceGroupName
  displayName: 'Resource Group Name'
  type: string
  default: 'YourResourceGroup'  # Replace with your desired default value
  values:
    - 'YourResourceGroup'  # Add allowed values if needed

- name: location
  displayName: 'Location'
  type: string
  default: 'East US'  # Replace with your desired Azure region

- name: dataLakeLinkedServiceName
  displayName: 'Data Lake Linked Service Name'
  type: string
  default: 'YourDataLakeLinkedServiceName'  # Replace with your actual linked service name

- name: vnetName
  displayName: 'VNet Name'
  type: string
  default: 'YourVNetName'  # Replace with your VNet name

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true

- task: AzureResourceGroupDeployment@2
  displayName: 'Deploy ARM Template'
  inputs:
    azureSubscription: 'YourAzureServiceConnection'  # Replace with your Azure service connection
    action: 'Create Or Update Resource Group'
    resourceGroupName: $(resourceGroupName)
    location: $(location)
    templateLocation: 'Linked artifact'
    csmFile: '$(System.DefaultWorkingDirectory)/ARM/adf.json'  # Replace with the path to your ARM template
    overrideParameters: 
      - '-dataFactoryName $(dataFactoryName)'
      - '-dataLakeLinkedServiceName $(dataLakeLinkedServiceName)'
    deploymentMode: 'Incremental'
